# Generated by Django 6.0.5 on 2026-06-13 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_profile_picture'),
        ('accounts', '0003_user_latitude_user_longitude'),
    ]

    operations = [
    ]
