# Generated by Django 6.0.5 on 2026-06-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='image',
        ),
        migrations.AddField(
            model_name='food_items',
            name='food_image',
            field=models.ImageField(default='food_images/default.jpg', upload_to='media/food_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_image',
            field=models.ImageField(default='default.jpg', upload_to='media/restaurant_images/'),
            preserve_default=False,
        ),
    ]
