# Generated by Django 6.0.5 on 2026-06-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_remove_restaurant_image_food_items_food_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_items',
            name='food_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/food_images/'),
        ),
    ]
