# Generated by Django 6.0.5 on 2026-06-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery_man',
            name='current_location',
        ),
        migrations.AddField(
            model_name='delivery_man',
            name='current_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery_man',
            name='current_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery_man',
            name='last_location_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
